# Generated by Django 3.2 on 2021-04-15 09:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_auto_20210415_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a webpage name', max_length=200)),
                ('url', models.CharField(help_text='Enter a webpage url', max_length=200)),
                ('description', models.CharField(help_text='Enter a webpage description', max_length=200)),
                ('tags', taggit.managers.TaggableManager(help_text='Enter webpage tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
