# Generated by Django 3.2 on 2021-04-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20210415_0945'),
        ('bookmarksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Bookmarks',
        ),
    ]
