# Generated by Django 3.2 on 2021-04-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksapp', '0002_rename_event_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the folder name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarksapp.folder'),
        ),
    ]
